name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: "moby-derp-test"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        ruby: ["2.7"]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup bundler
        run: |
          gem install bundler -v 2.1.4 --no-doc
          bundle config deployment 'true'
          bundle config without 'development'
          bundle config path vendor/bundle

      - name: Bundler cache
        uses: actions/cache@v1
        id: bundler-cache
        with:
          path: config/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Setup gems
        run: bundle install --jobs 4

      - name: RSpec
        run: bundle exec rspec
